/*==========================================================================*/
/*cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc*/
/*==========================================================================*/
/*                                                                          */
/*                         PI_MD:                                           */
/*             The future of simulation technology                          */
/*             ------------------------------------                         */
/*                   Module: test_energy.c                                  */
/*                                                                          */
/* This routine numerically checks forces and pressure tensors              */
/* generated by the energy routine                                          */
/*                                                                          */
/*==========================================================================*/
/*cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc*/
/*==========================================================================*/

#include "standard_include.h"
#include "../typ_defs/typedefs_gen.h"
#include "../typ_defs/typedefs_class.h"
#include "../typ_defs/typedefs_bnd.h"
#include "../proto_defs/proto_energy_ctrl_entry.h"
#include "../proto_defs/proto_energy_ctrl_local.h"
#include "../proto_defs/proto_intra_entry.h"
#include "../proto_defs/proto_intra_con_entry.h"
#include "../proto_defs/proto_surf_entry.h"
#include "../proto_defs/proto_real_space_entry.h"
#include "../proto_defs/proto_recip3d_entry.h"
#include "../proto_defs/proto_math.h"
#include "../proto_defs/proto_friend_lib_entry.h"
#include "../proto_defs/proto_communicate_wrappers.h"

/*==========================================================================*/
/*cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc*/
/*==========================================================================*/

void test_energy(CLASS *class, BONDED *bonded, GENERAL_DATA *general_data)

/*==========================================================================*/
/*         Begin Routine                                                    */ 
     {/*begin routine*/
/*==========================================================================*/
/*         Local Variable declarations                                      */
#include "../typ_defs/typ_mask.h"  
  int natm_mall   = class->clatoms_info.natm_tot;
  int natm_tot    = class->clatoms_info.natm_tot;
  int cubic_box_flag;
  int num_proc = class->communicate.np;
  int inter,iii,ioff;
  double delta,pvten_tmp[10];
  double fx_tmp,fy_tmp,fz_tmp,pvtenb_tmp;
  int ifp_check;
  int iperd,ninter;
  int ipart1,ipart2,ipart;
  int j,i,iatm,k,koff,joff;
  double vreal,vrecip,vself,vbgr,vlong,vsurf;
  double vvdw,vcoul;
  double vbond,vbend,vbend_bnd,vtors,vonfo,vecor,vonfo_vdw,vonfo_coul;
  double vbend_bnd_bond, vbend_bnd_bend;
  double vbond_free,vbend_free,vtors_free,vbar_free;
  double vwatts_tot,vwatts_bond,vwatts_bend;
  double *fx,*fy,*fz;
  double *sx,*sy,*sz;
  double *pvten,*hmatd;
  double vgen,vgen_p,vgen_m;
  double vgen2,vgen3;
  double fxb,fyb,fzb,pvtenb,cpu2,cpu1,cpu;
  double pext          = general_data->statepoint.pext;
  int myid             = class->communicate.myid;
  MPI_Comm comm_forc   = class->communicate.comm_forc;

/*==========================================================================*/
/* I)Initialize */

  /* mal_verify(1); */

  vlong       = 0.0;
  vself       = 0.0;
  vbgr        = 0.0;   
  vecor       = 0.0;
  vrecip      = 0.0;
  vvdw        = 0.0;
  vcoul       = 0.0;
  vreal       = 0.0;
  vsurf       = 0.0;
  vbond       = 0.0;
  vbend       = 0.0;
  vbend_bnd   = 0.0;
  vbend_bnd_bond   = 0.0;
  vbend_bnd_bend   = 0.0;
  vtors       = 0.0;
  vonfo       = 0.0;
  vonfo_vdw   = 0.0;
  vonfo_coul  = 0.0;
  vbond_free  = 0.0;
  vbend_free  = 0.0;
  vtors_free  = 0.0;
  vbar_free   = 0.0;
  vwatts_tot  = 0.0;
  vwatts_bond = 0.0;
  vwatts_bend = 0.0;

  fx    = (double *)cmalloc(natm_tot*sizeof(double))-1;
  fy    = (double *)cmalloc(natm_tot*sizeof(double))-1;
  fz    = (double *)cmalloc(natm_tot*sizeof(double))-1;
  sx    = (double *)cmalloc(natm_tot*sizeof(double))-1;
  sy    = (double *)cmalloc(natm_tot*sizeof(double))-1;
  sz    = (double *)cmalloc(natm_tot*sizeof(double))-1;
  pvten = (double *)cmalloc((size_t)9*sizeof(double))-1;
  hmatd = (double *)cmalloc((size_t)9*sizeof(double))-1;
  iperd = general_data->cell.iperd;
  gethinv((general_data->cell.hmat),(general_data->cell.hmati),
                                   &(general_data->cell.vol),iperd);
  class->for_scr.wght_ter        = 1.0;
  class->for_scr.wght_ter_res    = 1.0;
  bonded->intra_scr.wght_tra     = 1.0;
  bonded->intra_scr.wght_tra_res = 1.0;
  bonded->intra_scr.wght_ter     = 1.0;
  bonded->intra_scr.wght_ter_res = 1.0;
  for(ipart=1;ipart<= natm_tot;ipart++){
    sx[ipart] = 
           class->clatoms_pos[1].x[ipart]*general_data->cell.hmati[1]+
           class->clatoms_pos[1].y[ipart]*general_data->cell.hmati[4]+    
           class->clatoms_pos[1].z[ipart]*general_data->cell.hmati[7];
    sy[ipart] = 
           class->clatoms_pos[1].x[ipart]*general_data->cell.hmati[2]+
           class->clatoms_pos[1].y[ipart]*general_data->cell.hmati[5]+
           class->clatoms_pos[1].z[ipart]*general_data->cell.hmati[8];
    sz[ipart] = 
           class->clatoms_pos[1].x[ipart]*general_data->cell.hmati[3]+
           class->clatoms_pos[1].y[ipart]*general_data->cell.hmati[6]+
           class->clatoms_pos[1].z[ipart]*general_data->cell.hmati[9];
  }/*endfor*/

/*==========================================================================*/
/* II) Loop over all the interactions */

if(myid==0){
 printf("Do you wish to check forces and pressure tensor?(1 or 0)\n");
 scanf("%d",&ifp_check);
 if(ifp_check == 1) {
  printf("Enter the indices of two atoms whose force you wish checked\n");
  scanf("%d %d",&ipart1,&ipart2);printf("\n");
     if(ipart1 > natm_tot || ipart1 <= 0) {
      printf("The particle number %d you have chosen\n",ipart1);
      printf("is out of range  -- using first particle instead\n");   
      ipart1=1;
     }/*endif*/
     if(ipart2 > natm_tot || ipart2 <= 0) {
      printf("The particle number %d you have chosen\n",ipart2);
      printf("is out of range  -- using last particle instead\n");   
      ipart2=natm_tot;
     }/*endif*/
 }/*endif*/
}/*endif*/
if(num_proc>1){
 Bcast(&ifp_check,1,MPI_INT,0,comm_forc);
 if(ifp_check==1){
   Bcast(&ipart1,1,MPI_INT,0,comm_forc);
   Bcast(&ipart2,1,MPI_INT,0,comm_forc);
 }/*endif*/
}/*endif*/

  ninter = 16;
  delta = 1.e-07;
  for(inter=1; inter<=ninter; inter++){

/*---------------------------------------------------------------------------*/
/* A) Get the true force */

  if(myid==0){
    printf("===============\n");
    if(inter==1) {printf("Checking real_space inter\n");}
    if(inter==2) {printf("Checking long\n");}
    if(inter==3) {printf("Checking ewald: alp = %.10g A^(-1)\n",
                  (general_data->ewald.alp_ewd/BOHR));}
    if(inter==4) {printf("Checking bkgr \n");}
    if(inter==5) {printf("Checking bonds\n");}
    if(inter==6) {printf("Checking bends\n");}
    if(inter==7) {printf("Checking tors \n");}
    if(inter==8) {printf("Checking onfos\n");}
    if(inter==9) {printf("Checking ecors\n");}
    if(inter==10) {printf("Checking Uri-Bradleys\n");}
    if(inter==11) {printf("Checking free-energy bonds\n");}
    if(inter==12) {printf("Checking free-energy bends\n");}
    if(inter==13) {printf("Checking free-energy tors\n");}
    if(inter==14) {printf("Checking watts intramolecular potential\n");}
    if(inter==15) {printf("Checking rbar-sigma free energy potential\n");}
    if(inter==16) {printf("Checking surface potential\n");}
    printf("---------------\n\n");
  }
    get_ghost_pos(&(class->clatoms_info),&(class->clatoms_pos[1]),
                   &(class->ghost_atoms));
    if(num_proc > 1) Barrier(comm_forc);
    cputime(&cpu1); 
    test_force(class,bonded,general_data,inter,&vgen,&vgen2,&vgen3); 
    cputime(&cpu2); 
    cpu = cpu2-cpu1;
    communicate_test_energy( &vgen, &vgen2, &vgen3, &cpu,comm_forc,
			     num_proc);
  if(myid==0){
    if(inter==1){printf("The real_space inter energy is %.13g; cputime %g\n",
                 vgen,cpu);
                 vreal=vgen;vcoul=vgen2;vvdw=vgen3;}
    if(inter==2){printf("The long range correction is %.13g; cputime %g \n",
                         vgen,cpu);
                 vlong=vgen;}
    if(inter==3){printf("The recip energy is %.13g; cputime %g\n",vgen,cpu);
                 vrecip=vgen;}
    if(inter==4){
        printf("The background energy is %.13g vself is %.13g; cputime %g\n",
                         vgen,vgen2,cpu);vbgr=vgen;vself=vgen2;}
    if(inter==5){printf("The bond  energy is %.13g; cputime %g\n",vgen,cpu);
                 vbond=vgen;}
    if(inter==6){printf("The bend  energy is %.13g; cputime %g\n",vgen,cpu);
                 vbend=vgen;}
    if(inter==7){printf("The tors  energy is %.13g; cputime %g\n",vgen,cpu);
                 vtors=vgen;}
    if(inter==8){printf("The onfo  energy is %.13g; cputime %g\n",vgen,cpu);
                 vonfo=vgen;vonfo_vdw=vgen2;vonfo_coul=vgen3;}
    if(inter==9){printf("The ecor  energy is %.13g; cputime %g\n",vgen,cpu);
                 vecor=vgen;}
    if(inter==10){printf("The Uri-Bradley energy is %.13g; cputime %g\n",
                          vgen,cpu);vbend_bnd=vgen;
                                    vbend_bnd_bond = vgen3;
                                    vbend_bnd_bend = vgen2;}
    if(inter==11){printf("The free bond energy is %.13g; cputime %g\n",
                          vgen,cpu);vbond_free=vgen;}
    if(inter==12){printf("The free bend energy is %.13g; cputime %g\n",
                          vgen,cpu);vbend_free=vgen;}
    if(inter==13){printf("The free tors energy is %.13g; cputime %g\n",
                          vgen,cpu);vtors_free=vgen;}

    if(inter==14){printf("The watts energy is %.13g; cputime %g\n",
                          vgen,cpu);vwatts_tot=vgen;vwatts_bond=vgen2;
                                    vwatts_bend=vgen3;}
    if(inter==15){printf("The rbar-sigma energy is %.13g; cputime %g\n",
                          vgen,cpu);vbar_free=vgen;}
    if(inter==16){printf("The surface energy is %.13g; cputime %g\n",
                          vgen,cpu); vsurf=vgen;}
  }
/*---------------------------------------------------------------------------*/
/* B) Save the force and pressure tensor                                     */

   if(ifp_check == 1) {
    for(ipart=1;ipart<= natm_tot;ipart++){
      fx[ipart] = class->clatoms_pos[1].fx[ipart]; 
      fy[ipart] = class->clatoms_pos[1].fy[ipart]; 
      fz[ipart] = class->clatoms_pos[1].fz[ipart]; 
    }/*endfor*/
    for(j=1;j<=9;j++){
      pvten[j]  = general_data->ptens.pvten_tot[j];
    }/*endfor*/
   }/*endif*/

/*---------------------------------------------------------------------------*/
/* C) Get the numerical force */

   if(ifp_check == 1) {
     for(iatm=1;iatm<=2;iatm++){
      if(iatm==1){i=ipart1;}
      if(iatm==2){i=ipart2;}
/*  i) X forces */
      class->clatoms_pos[1].x[i] += delta;
      get_ghost_pos(&(class->clatoms_info),&(class->clatoms_pos[1]),
                    &(class->ghost_atoms));
      test_force(class,bonded,general_data,inter,&vgen_p,&vgen2,&vgen3); 
      communicate_test_energy( &vgen_p, &vgen2, &vgen3, &cpu,comm_forc,
			       num_proc);
      class->clatoms_pos[1].x[i] -= (2.0*delta);
      get_ghost_pos(&(class->clatoms_info),&(class->clatoms_pos[1]),
                    &(class->ghost_atoms));
      test_force(class,bonded,general_data,inter,&vgen_m,&vgen2,&vgen3); 
      communicate_test_energy( &vgen_m, &vgen2, &vgen3, &cpu,comm_forc,
			       num_proc);
      class->clatoms_pos[1].x[i] += delta;
      fxb = (vgen_m-vgen_p)/(2.0*delta);
/*  ii) Y forces */
      class->clatoms_pos[1].y[i] += delta;
      get_ghost_pos(&(class->clatoms_info),&(class->clatoms_pos[1]),
                    &(class->ghost_atoms));
      test_force(class,bonded,general_data,inter,&vgen_p,&vgen2,&vgen3); 
      communicate_test_energy( &vgen_p, &vgen2, &vgen3, &cpu,comm_forc,
			       num_proc);
      class->clatoms_pos[1].y[i] -= (2.0*delta);
      get_ghost_pos(&(class->clatoms_info),&(class->clatoms_pos[1]),
                    &(class->ghost_atoms));
      test_force(class,bonded,general_data,inter,&vgen_m,&vgen2,&vgen3); 
       communicate_test_energy( &vgen_m, &vgen2, &vgen3, &cpu,comm_forc,
                                num_proc);
      class->clatoms_pos[1].y[i] += delta;
      fyb = (vgen_m-vgen_p)/(2.0*delta);
/*  iii) Z forces */
      class->clatoms_pos[1].z[i] += delta;
      get_ghost_pos(&(class->clatoms_info),&(class->clatoms_pos[1]),
                    &(class->ghost_atoms));
      test_force(class,bonded,general_data,inter,&vgen_p,&vgen2,&vgen3); 
       communicate_test_energy( &vgen_p, &vgen2, &vgen3, &cpu,comm_forc,
                                num_proc);
      class->clatoms_pos[1].z[i] -= (2.0*delta);
      get_ghost_pos(&(class->clatoms_info),&(class->clatoms_pos[1]),
                    &(class->ghost_atoms));
      test_force(class,bonded,general_data,inter,&vgen_m,&vgen2,&vgen3); 
       communicate_test_energy( &vgen_m, &vgen2, &vgen3, &cpu,comm_forc,
                                num_proc);
      class->clatoms_pos[1].z[i] += delta;
      fzb = (vgen_m-vgen_p)/(2.0*delta);
/*  iv) Print out */
      if(num_proc>1){
        fx_tmp = fx[i];
        Allreduce(&fx_tmp,&fx[i], 1, MPI_DOUBLE, MPI_SUM,0, comm_forc);
        fy_tmp = fy[i];
        Allreduce(&fy_tmp,&fy[i], 1, MPI_DOUBLE, MPI_SUM,0, comm_forc);
        fz_tmp = fz[i];
        Allreduce(&fz_tmp,&fz[i], 1, MPI_DOUBLE, MPI_SUM,0, comm_forc);
      }/*endif*/
      if(myid==0){
        printf("atm %d fx_num %.13g fx %.13g\n",i,fxb,fx[i]);
        printf("atm %d fy_num %.13g fy %.13g\n",i,fyb,fy[i]);
        printf("atm %d fz_num %.13g fz %.13g\n",i,fzb,fz[i]);
      }/*endif*/
     }/*endfor:iatm*/ 

/*---------------------------------------------------------------------------*/
/* D) Construct the numerical pressure tensor                                */

     cubic_box_flag = general_data->cell.cubic_box_flag;
     general_data->cell.cubic_box_flag = 0;
     for(j=1;j<=9;j++){ 

        general_data->cell.hmat[j] +=  delta;
        for(ipart=1;ipart<= natm_tot;ipart++){
          class->clatoms_pos[1].x[ipart] =
                                 sx[ipart]*general_data->cell.hmat[1]
                                +sy[ipart]*general_data->cell.hmat[4]
                                +sz[ipart]*general_data->cell.hmat[7];
          class->clatoms_pos[1].y[ipart] = 
                                 sx[ipart]*general_data->cell.hmat[2]
                                +sy[ipart]*general_data->cell.hmat[5]
                                +sz[ipart]*general_data->cell.hmat[8];
          class->clatoms_pos[1].z[ipart] = 
                                 sx[ipart]*general_data->cell.hmat[3]
                                +sy[ipart]*general_data->cell.hmat[6]
                                +sz[ipart]*general_data->cell.hmat[9];
        }/*endfor:ipart*/
        gethinv((general_data->cell.hmat),(general_data->cell.hmati),
                                &(general_data->cell.vol),iperd);
        get_ghost_pos(&(class->clatoms_info),&(class->clatoms_pos[1]),
                       &(class->ghost_atoms));
        test_force(class,bonded,general_data,inter,&vgen_p,&vgen2,&vgen3); 
         communicate_test_energy( &vgen_p, &vgen2, &vgen3, &cpu,comm_forc,
                                  num_proc);

        general_data->cell.hmat[j] -= (2.0*delta);
        for(ipart=1;ipart<= natm_tot;ipart++){
          class->clatoms_pos[1].x[ipart] = 
                                  sx[ipart]*general_data->cell.hmat[1]
                                 +sy[ipart]*general_data->cell.hmat[4]
                                 +sz[ipart]*general_data->cell.hmat[7];
           class->clatoms_pos[1].y[ipart] = 
                                  sx[ipart]*general_data->cell.hmat[2]
                                 +sy[ipart]*general_data->cell.hmat[5]
                                 +sz[ipart]*general_data->cell.hmat[8];
           class->clatoms_pos[1].z[ipart] = 
                                  sx[ipart]*general_data->cell.hmat[3]
                                 +sy[ipart]*general_data->cell.hmat[6]
                                 +sz[ipart]*general_data->cell.hmat[9];
        }/*endfor:ipart*/
        gethinv((general_data->cell.hmat),(general_data->cell.hmati),
                                               &(general_data->cell.vol),
                iperd);
        get_ghost_pos(&(class->clatoms_info),&(class->clatoms_pos[1]),
                      &(class->ghost_atoms));
        test_force(class,bonded,general_data,inter,&vgen_m,&vgen2,&vgen3); 
         communicate_test_energy( &vgen_m, &vgen2, &vgen3, &cpu,comm_forc,
                                  num_proc);

        general_data->cell.hmat[j]  += delta;
        hmatd[j] = (vgen_m-vgen_p)/(2.0*delta);
    }/*endfor*/

    general_data->cell.cubic_box_flag = cubic_box_flag;
    gethinv((general_data->cell.hmat),(general_data->cell.hmati),
                             &(general_data->cell.vol),iperd);
    if(num_proc>1){
     for(i=1;i<=9;i++){pvten_tmp[i]=pvten[i];}
     Allreduce(&pvten_tmp[1],&pvten[1], 9, MPI_DOUBLE, MPI_SUM,0, comm_forc);
   }/*endif*/
    for(i=1;i<=3;i++){
      ioff = (i-1)*3; 
      for(j=1;j<=3;j++){
        joff = (j-1)*3;
        pvtenb = 0.0;
        for(k=1;k<=3;k++){
         koff = (k-1)*3;
         pvtenb += general_data->cell.hmat[(j+koff)]*hmatd[(i+koff)];
        }/*endfor*/
        if(inter==2&&class->energy_ctrl.iswit_vdw<=0){pvtenb*=2.0;}
        if(myid==0){
         printf("P%d%d_num %.13g P%d%d %.13g\n",
                               i,j,pvtenb,i,j,pvten[(i+joff)]);
        }/*endif*/
      }/*endfor*/
    }/*endfor*/     
  }/* endif ifp_check */
/*---------------------------------------------------------------------------*/
/* E) Completed test                                                         */

 if(myid==0){
                 printf("\n---------------\n");
    if(inter==1){printf("Finished real_space inter\n");}
    if(inter==2){printf("Finished long \n");}
    if(inter==3){printf("Finished ewald\n");}
    if(inter==4){printf("Finished bkgr \n");}
    if(inter==5){printf("Finished bonds\n");}
    if(inter==6){printf("Finished bends\n");}
    if(inter==7){printf("Finished tors \n");}
    if(inter==8){printf("Finished onfos\n");}
    if(inter==9){printf("Finished ecors\n");}
    if(inter==10){printf("Finished Uri-Bradleys\n");}
    if(inter==11){printf("Finished free bonds \n");}
    if(inter==12){printf("Finished free bends \n");}
    if(inter==13){printf("Finished free tors  \n");}
    if(inter==14){printf("Finished Watts  \n");}
    if(inter==15){printf("Finished rbar-sigma  \n");}
    if(inter==16){printf("Finished surface  \n");}
    printf("===============\n\n");
    printf("Enter an integer to continue:  ");scanf("%d",&iii);
    printf("\n");
 }/* endif : myid=0 */
  }/*endfor*/ 

/*==========================================================================*/
/* III) Assign energies */

    vrecip                     += vself+vbgr+vecor;
    vreal                      += vlong+vonfo;
    vvdw                       += vlong + vonfo_vdw + vsurf;
    vcoul                      += vrecip+vonfo_coul;
    general_data->stat_avg.vintert    = vreal+vrecip;
    general_data->stat_avg.vrecip     = vrecip;
    general_data->stat_avg.vvdw       = vvdw;
    general_data->stat_avg.vsurft     = vsurf;
    general_data->stat_avg.vcoul      = vcoul;
    general_data->stat_avg.vbondt     = vbond;
    general_data->stat_avg.vbendt     = vbend;
    general_data->stat_avg.vbend_bndt = vbend_bnd;
    general_data->stat_avg.vbend_bnd_bend = vbend_bnd_bend;
    general_data->stat_avg.vbend_bnd_bond = vbend_bnd_bond;
    general_data->stat_avg.vtorst     = vtors;
    general_data->stat_avg.vbond_free = vbond_free;
    general_data->stat_avg.vbend_free = vbend_free;
    general_data->stat_avg.vtors_free = vtors_free;
    general_data->stat_avg.vbar_free  = vbar_free;
    general_data->stat_avg.vonfot     = vonfo;
    general_data->stat_avg.vintrat    = (vbond+vbend+vbend_bnd+vtors
				   +vbond_free+vbend_free+vtors_free);
    general_data->stat_avg.vbondt_watts = vwatts_bond;
    general_data->stat_avg.vbendt_watts = vwatts_bend;
    general_data->stat_avg.vtot_watts   = vwatts_tot;
#ifdef DEBUG
    if(class->energy_ctrl.isep_vvdw == 1) {
     printf("Van der Waals energy %.13g\n",vvdw);
     printf("Coulomb energy %.13g\n",vcoul);
    }
#endif
/*==========================================================================*/
/* IV) Done */

  cfree(&(fx[1]));
  cfree(&(fy[1]));
  cfree(&(fz[1]));
  cfree(&(sx[1]));
  cfree(&(sy[1]));
  cfree(&(sz[1]));
  cfree(&(pvten[1]));
  cfree(&(hmatd[1]));

  /*-------------------------------------------------------------------*/
}/*end routine */
/*==========================================================================*/




/*==========================================================================*/
/*cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc*/
/*==========================================================================*/

void test_force(CLASS *class, BONDED *bonded, GENERAL_DATA *general_data,
                int inter,double *vgen, double *vgen2, double *vgen3 )

/*==========================================================================*/
{/*begin Routine */
/*==========================================================================*/
/*       Local Variables                                                    */

 double vvdw,vcoul;
 double vself,vbgr,vlong,vol;
 int ipart,j,iii,iver_get,irespa;
 int pi_beads         = class->clatoms_info.pi_beads; 
 int ires_bond        = 0;
 double pext          = general_data->statepoint.pext;
 int error_check_on   = general_data->error_check_on;
 double *clus_corr_r  = general_data->ewald.clus_corr_r;
 double *dclus_corr_r = general_data->ewald.dclus_corr_r;
 int myid             = class->communicate.myid;
 int   natm_tot       = class->clatoms_info.natm_tot;
 double vwatts_bend,vwatts_bond,vwatts_tot;
 class->energy_ctrl.iget_pv_real_inter = 1;
 class->energy_ctrl.iget_pe_real_inter = 1;

/*==========================================================================*/

    iver_get = 0;
    *vgen = 0.0;
    *vgen2 = 0.0;
    *vgen3 = 0.0;

    for(ipart=1;ipart<= natm_tot;ipart++){
     class->clatoms_pos[1].fx[ipart] = 0.0;
     class->clatoms_pos[1].fy[ipart] = 0.0;
     class->clatoms_pos[1].fz[ipart] = 0.0;
    }/*endfor*/

    for(j=1;j<=9;j++){
      general_data->ptens.pvten[j]     = 0.0;
      general_data->ptens.pvten_tot[j] = 0.0;
    }/*endfor*/

    if(inter==1){
       vvdw=0.0;vcoul=0.0;
       force_control(&(class->clatoms_info),&(class->clatoms_pos[1]), 
                       &(class->for_scr),
                       &(class->atommaps),&(general_data->cell),
                       &(general_data->ptens),   &(class->interact),
                       &(class->energy_ctrl),&(class->nbr_list),
                       &(bonded->excl),    &(bonded->intra_scr),vgen,
		       &vvdw,&vcoul,error_check_on,
                       &(class->class_comm_forc_pkg));
       *vgen2 = vcoul;
       *vgen3 = vvdw;
    }/*endif*/
    if(inter==2){
       vol = general_data->cell.vol;
       if(general_data->cell.iperd==3){
         if(myid==0){
          long_range_corr(pi_beads,vgen,vol,
                          &(general_data->ptens),&(class->for_scr),
                          &(class->interact),&(class->energy_ctrl),pext);
         }/*endif*/
       }/*endif*/
    }/*endif*/

    if((class->clatoms_info.nchrg>0)&&(general_data->cell.iperd>0)
                                                      &&(inter==3)){
      if(class->part_mesh.pme_on==0){
       ewald3d_recip(&(class->clatoms_info),&(class->clatoms_pos[1]),
                     &(general_data->cell),
                     &(general_data->ptens),(general_data->ewald.alp_ewd),
                     (general_data->ewald.alp_clus),
                     (general_data->ewald.nktot),(general_data->ewald.kastr),
                     (general_data->ewald.kbstr),(general_data->ewald.kcstr),
                     (general_data->ewald.ibrk1),(general_data->ewald.ibrk2),
                     &(class->ewd_scr),vgen,
                     (class->for_scr.wght_ter_res),iver_get,
                     &(class->class_comm_forc_pkg),
                     class->energy_ctrl.iget_pv_real_inter, 
                     clus_corr_r,dclus_corr_r);
      }else{
       irespa = 0;
       ewald3d_recip_pme(&(class->clatoms_info),&(class->clatoms_pos[1]),
                        &(general_data->cell),
                        &(general_data->ptens),(general_data->ewald.alp_ewd),
                        (general_data->ewald.nktot),
                        (general_data->ewald.kastr),
                        (general_data->ewald.kbstr),
                        (general_data->ewald.kcstr),
                        &(class->ewd_scr),vgen,
                        (class->for_scr.wght_ter_res),iver_get,
                        &(class->part_mesh),irespa,
                        &(class->class_comm_forc_pkg),
                        class->energy_ctrl.iget_pv_real_inter,
                        &(general_data->pme_fft_pkg),&(class->for_scr),                                clus_corr_r,dclus_corr_r);
     }/*endif*/
    }/*endif*/
    if((class->clatoms_info.nchrg>0)&&(general_data->cell.iperd>0)
                                                         &&(inter==4)){
       vol = general_data->cell.vol;
      ewald3d_selfbgr(&(class->clatoms_info),&general_data->ewald,
                      &(general_data->ptens),vol,
                      (bonded->intra_scr.wght_tra_res),&vself,&vbgr,
                      (class->communicate.np_forc),
                      class->energy_ctrl.iget_pv_real_inter,
                      general_data->cell.iperd);
      *vgen  = vbgr;
      *vgen2 = vself;
    }/*endif*/

  /*======================================================================*/
  /* V) Get intramolecular group bond Watts         */


    if((bonded->grp_bond_watts.num_33)!=0&&(inter==14)){
        vwatts_bend = 0.0;
        vwatts_bond = 0.0;
        vwatts_tot = 0.0;
         bond_watts_33(&(class->clatoms_info),&(class->clatoms_pos[1]),
                &(bonded->grp_bond_watts),&(general_data->cell),
                &(bonded->intra_scr),&(general_data->ptens),&vwatts_bend,
                &vwatts_bond,&vwatts_tot,iver_get,
                &(class->class_comm_forc_pkg),
                class->energy_ctrl.iget_pv_real_inter);
        *vgen = vwatts_tot;
        *vgen2 = vwatts_bond;
        *vgen3 = vwatts_bend;
    }/*endif*/

    if((bonded->bond.npow!=0)&&(inter==5)){
      bond(&(class->clatoms_info),&(class->clatoms_pos[1]),
              &(bonded->bond),&(general_data->cell),
              &(bonded->intra_scr),&(general_data->ptens),vgen,iver_get,
              ires_bond,&(class->class_comm_forc_pkg),
              class->energy_ctrl.iget_pv_real_inter);
    }/*endif*/
     
    if((bonded->bend.npow!=0)&&(inter==6)){
      bend(&(class->clatoms_info),&(class->clatoms_pos[1]),
            &(bonded->bend),&(general_data->cell),
            &(bonded->intra_scr),&(general_data->ptens),vgen,iver_get,
            &(class->class_comm_forc_pkg),
            class->energy_ctrl.iget_pv_real_inter);
    }/*endif*/

    if((bonded->tors.npow!=0)&&(inter==7)){
      tors(&(class->clatoms_info),&(class->clatoms_pos[1]),
           &(bonded->tors),&(general_data->cell),
           &(bonded->intra_scr),&(general_data->ptens),vgen,iver_get,
           &(class->class_comm_forc_pkg),
           class->energy_ctrl.iget_pv_real_inter);
    }/*endif*/

    if((bonded->onfo.num!=0)&&(inter==8)){
      onfo(&(class->clatoms_info),&(class->clatoms_pos[1]),
           &(bonded->onfo),&(general_data->cell),
           &(bonded->intra_scr),&(general_data->ptens),
           vgen,vgen2,vgen3,iver_get,
           &(class->class_comm_forc_pkg),
           class->energy_ctrl.iget_pv_real_inter);
    }/*endif*/

    if((bonded->ecor.num!=0)&&(inter==9)){
      ecor(&(class->clatoms_info),&(class->clatoms_pos[1]),
           &(bonded->ecor),&(general_data->cell),
           &(bonded->intra_scr),&(general_data->ptens),vgen,iver_get,
           &(class->class_comm_forc_pkg),
           class->energy_ctrl.iget_pe_real_inter,
           class->energy_ctrl.iget_pv_real_inter);
    }/*endif*/

    if((bonded->bend_bnd.num!=0)&&(inter==10)){
      bend_bnd(&(class->clatoms_info),&(class->clatoms_pos[1]),
               &(bonded->bend_bnd),&(general_data->cell),
               &(bonded->intra_scr),&(general_data->ptens),vgen,vgen2,vgen3,
               iver_get,&(class->class_comm_forc_pkg),
               class->energy_ctrl.iget_pv_real_inter);
    }/*endif*/

    if((bonded->bond_free.num!=0)&&(inter==11)){
      bond_free(&(class->clatoms_info)  ,&(class->clatoms_pos[1])  ,
                &(bonded->bond_free),&(general_data->cell),
                &(bonded->intra_scr),&(general_data->ptens),vgen,
                &(class->energy_ctrl),class->communicate.np_forc);
    }/*endif*/
    if((bonded->bend_free.num!=0)&&(inter==12)){
      bend_free(&(class->clatoms_info)  ,&(class->clatoms_pos[1])  ,
                &(bonded->bend_free),&(general_data->cell),
                &(bonded->intra_scr),&(general_data->ptens),vgen,
                &(class->energy_ctrl),class->communicate.np_forc);
    }/*endif*/
    if((bonded->tors_free.num!=0)&&(inter==13)){
      tors_free(&(class->clatoms_info)  ,&(class->clatoms_pos[1])  ,
                &(bonded->tors_free),&(general_data->cell),
                &(bonded->intra_scr),&(general_data->ptens),vgen,
                &(class->energy_ctrl),class->communicate.np_forc);
    }/*endif*/

    if( (bonded->rbar_sig_free.nfree!=0) && (inter==15) ){
      rbar_sig_free(&(class->clatoms_info),&(class->clatoms_pos[1]),
                    &(bonded->rbar_sig_free),&(general_data->cell),
                    &(bonded->intra_scr),&(general_data->ptens),vgen, 
                    &(class->energy_ctrl),class->communicate.np_forc);
    }/*endif*/

    if( (class->surface.isurf_on != 0) && (inter == 16) ){
       surf_pot(&(class->clatoms_info),&(class->clatoms_pos[1]),
                &(class->atommaps),&(class->surface),&(general_data->cell),
                &(bonded->intra_scr),&(general_data->ptens),vgen,
                iver_get,&(class->class_comm_forc_pkg),
                class->energy_ctrl.iget_pv_real_inter, 
                class->energy_ctrl.iget_pe_real_inter);
    }/*endif*/

/*==========================================================================*/
/* Distribute ghost forces into atom forces                            */

   distrib_ghost_force(&(class->clatoms_info),&(class->clatoms_pos[1]),
                        &(class->ghost_atoms),iver_get);

/*-------------------------------------------------------------------*/
    }/*end routine */
/*==========================================================================*/



/*==========================================================================*/
/*cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc*/
/*==========================================================================*/

void communicate_test_energy(double *vgen,double *vgen2,double *vgen3,
                             double *cpu, MPI_Comm world,int num_proc)

/*==========================================================================*/
/*         Begin Routine                                                    */ 
     {/*begin routine*/
/*==========================================================================*/

#include "../typ_defs/typ_mask.h"

     int iii;
     double vgen_temp,vgen2_temp,vgen3_temp,cpu_temp;

     cpu_temp = *cpu;
     vgen_temp = *vgen;
     vgen2_temp = *vgen2;
     vgen3_temp = *vgen3;
  if(num_proc > 1){
     Reduce(&cpu_temp,cpu, 1, MPI_DOUBLE, MPI_MAX, 0,world); 
     Allreduce(&vgen_temp,vgen, 1, MPI_DOUBLE, MPI_SUM,0, world);
     Allreduce(&vgen2_temp,vgen2, 1, MPI_DOUBLE, MPI_SUM,0, world);
     Allreduce(&vgen3_temp,vgen3, 1, MPI_DOUBLE, MPI_SUM,0, world);
     Barrier(world);
  }/*endif*/

/*--------------------------------------------------------------------------*/
  }/*end routine*/
/*==========================================================================*/




